### ISSUE TITLE
file not generated 

### ISSUE THREAD

**Issue by IeuanWalker** [varunsridharan/grunt-combine-files#11]
I have the follwoing in gruntfile - 

```js
    combine_files: {
            options: {
                append: false,
                prepend: 'fileappend', // Use it as //@fileappend filename.js
                add: 'inline', // Use it as //@inline filename.js
            },
            files: {
                "wwwroot/js/main.js": [
                    'wwwroot/js/Vendors/Bootstrap/bootstrap.js',
                    'wwwroot/js/Vendors/Datatables/datatables.js',
                    'wwwroot/js/Vendors/Toaster/toaster.min.js',
                    'wwwroot/js/Vendors/JQuery/jquery.js',
                ],
            },
        },
```

and when i run it says it done, but the main.js file isnt generated -

```
C:\Users\c773975\source\repos\StockistManager\StockistManager> cmd.exe /c grunt -b "C:\Users\c773975\source\repos\StockistManager\StockistManager" --gruntfile "C:\Users\c773975\source\repos\StockistManager\StockistManager\Gruntfile.js" combine_files --color
Running "combine_files:files" (combine_files) task
Done.
```

**Comment by varunsridharan** [comment]
@IeuanWalker Well. i haven't tested the way you used it. but i tested it as by creating it in a task and then using it
for more info please check it : https://github.com/varunsridharan/grunt-combine-files/blob/master/Gruntfile.js

<blockquote><img src="https://avatars3.githubusercontent.com/u/1884287?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/varunsridharan/grunt-combine-files">varunsridharan/grunt-combine-files</a></strong></div><div>This plugin will allow you to combine multiple JS files using (@grunt-append / @grunt-prepend / @grunt-inline) - varunsridharan/grunt-combine-files</div></blockquote>
